language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: AdiQfBJxA8gZoDiwbxZIwvZxy4OKn1Lj9KOQBJusOMcz5qWBPVK4JRHJxz1MeKo/ctchxGVSHSO7JL34bbaMk4RRnObrr7b9P3B/FbVuWVNFM0sqgIInBNRdG1sD5dlFEavmndNb9HSM8cuvwOUr9ApbBhadl9DD4usXp4gUdjqdN6CSw9E7NUmHl54tg1KAXkKZUx+e+oG+OYbx60sU6W2GdsZubSFAiqi6Prm6lzFRX9ZcBnOQ6WAEF7ybUDcUlkovi+4X4Oy460EZ6UwPwRfQ9K4SzdHz9t7YjuwTYn8Q7VtXEeJoebF2WDDCZKSoPeoHmcy7F6PKH+GUXoysYRixTs8NU4KzFIwFR8v5rcwyM6NOG4RsLiq5HOgMZnnx5K1gQQMHXX6WIeXOJ05YLQJzRtjF/QBMBEa7DhzSlCAWBBHkuPYNEa5L6BOZOAynk+xge5/lm4QD6fOCBaU3Pv8LYUnOGJMwS+0JhZQ8hguxooM4g/RGyt6xOV+NB7G7z3UT/+kB6AgOUkc5XXv4reATj2Z1UurB9Mo2nNzsFDc3+iGFJsiOHlxkX6xE5H4TTt5GzQFM4jxAhbgp/NZeMF/ZKZStM9xnV6HNHYG8BoOwfdW6WL6pARnew57IoGYOUCLKCo8Ue+f7753cKIAH0YvXyHGVd9zeYdaHX1V4HKk=
